include:
  - tests/ci_tests.yml

stages:
  - test
  - build_and_publish

build_and_publish:
  stage: build_and_publish
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME == "master"'
      changes:
        - Dockerfile
        - docker-entrypoint.sh
        - poetry.lock
        - pyproject.toml
        - src/*
  before_script:
    - echo $DOCKER_USERNAME
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE_NAME -f Dockerfile .
    - docker push $DOCKER_IMAGE_NAME
