version: '3.9'

name: ftiad-mlops-hw
services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address :9001
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

  create_buckets:
    container_name: create_buckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/first;
      /usr/bin/mc policy set public myminio/first;
      exit 0;
      "

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 5s
      retries: 5

  fast_api:
    build: .
    container_name: fast_api
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - minio
      - create_buckets
